language: ruby
rvm:
  - 2.3.0

branches:
    only:
        - master

script:
  - bundle exec rubocop
  - bundle exec scss-lint
  - bundle exec rake jshint
  - bundle exec rake

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
