language: ruby
rvm:
  - 2.3.0

branches:
    only:
        - master

script:
  - bundle exec rake lint
  - bundle exec rake

bundler_args: "--without development"
cache:
  - bundler

notifications:
  email: false
