openapi: '3.0.0'
info:
  version: 0.0.1
  title: Veteran Confirmation
  description: |

    ## Background

    This API allows approved third-parties to request confirmation from the
    VA of an individual's Veteran status.

    ## Design

    ### Authorization

    API requests are authorized through a symmetric API token, provided in an HTTP header with name `apikey`.

  termsOfService: ''
  contact:
    name: developer.va.gov
tags:
  - name: veteran_confirmation_status
    description: Veteran Confirmation - Veteran Status
servers:
  - url: https://dev-api.va.gov/services/veteran_confirmation/{version}
    description: VA.gov API development environment
    variables:
      version:
        default: v0
  - url: https://staging-api.va.gov/services/veteran_confirmation/{version}
    description: VA.gov API staging environment
    variables:
      version:
        default: v0
  - url: https://api.va.gov/services/veteran_confirmation/{version}
    description: VA.gov API production environment
    variables:
      version:
        default: v0
paths:
  /status:
    post:
      tags:
        - veteran_confirmation_status
      summary: Get confirmation about an individual's Veteran status according to the VA
      operationId: getVeteranStatus
      security:
        - apikey: []
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VeteranStatusRequest'
      responses:
        '200':
          description: Confirmation status successfully retrieved
          content:
            application/json:
              schema:
                required:
                  - data
                properties:
                  data:
                    $ref: '#/components/schemas/VeteranStatusConfirmation'
        '503':
          description: We encountered a temporary error. Check back in the future. 
components:
  securitySchemes:
    apikey:
      type: apiKey
      name: apikey
      in: header
  schemas:
    VeteranStatusRequest:
      description: Attributes required to retrieve a veteran's status
      type: object
      properties:
        ssn:
          type: string
          description: Social Security Number for the person of interest with or without dashes
          example: "555-55-5555"
        first_name:
          type: string
          description: First name for the person of interest
          example: "John"
        last_name:
          type: string
          description: Last name for the person of interest
          example: "Doe"
        birth_date:
          type: string
          description: Birth date for the person of interest in any valid ISO8601 format
          example: "1965-01-01"
    VeteranStatusConfirmation:
      description: |
        Veteran status confirmation for an individual
      type: object
      properties:
        type:
          type: string
          example: veteran_status_confirmations
        attributes:
          type: object
          properties:
            veteran_status:
              type: string
              description: |
                Whether the system could confirm the Veteran status of an invidual based on traits
              enum:
                - confirmed
                - not confirmed
