default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  url: <%= Settings.database_url %>

test:
  url: <%= Settings.test_database_url %><%= ENV['TEST_ENV_NUMBER'] %>

production:
  url: <%= Settings.database_url %>
