veteranFullName: [identity_information, full_name]
veteranSocialSecurityNumber: [identity_information, ssn]
vaFileNumber: 
veteranDateOfBirth: [identity_information, date_of_birth]
veteranAddress: [contact_information, address]
veteranPhone: [contact_information, us_phone]
