openapi: '3.0.0'
info:
  version: 0.0.1
  title: Veteran Verification
  description: |

    ## Background

    The use-case of this API is to allow third-parties to do the following after
    receiving authorization using an Open ID Connect flow: 

    #### Veteran Status - Request confirmation from the VA of an individual's Veteran status 

    The Veteran Verification API passes requests through to eMIS, the Enterprise
    Military Information Service, and formats the response into consumable data.

     #### Disability Rating - Access the disability rating of a Veteran

    The Disability Rating API passes requests through to EVSS, the Electronic Veterans Self Service, and formats the response into consumable data.

    #### Service History - Access the service history of a Veteran

    The Service History API passes requests through to eMIS, the Enterprise
    Military Information Service, and formats the response into consumable data.
  
    ## Design

    ### Authorization

    API requests are authorized using a Bearer token issued through an OpenID
    Connect service to allow third-party applications. The token should be
    submitted as an `Authorization` header in the form `Bearer <token>`.

    ### Veteran Status Request

    Allows a third-party application to request the VA confirm the Veteran Status of an
    authorized individual:

    1. Client Request: GET https://api.va.gov/services/veteran_verification/v0/status
       * Provide the Bearer token as a header: `Authorization: Bearer <token>`

    2. Status Response: A JSON API object with the individual's veteran status

    ### Disability Rating Request

    Allows a third-party application to request a Veteran's disability rating with the authorization of the Veteran.

    1. Client Request: GET https://dev-api.va.gov/services/veteran_verification/v0/disability_rating
       *  Provide the Bearer token as a header: `Authorization: Bearer <token>`

    2. Service Response: A JSON API object with the Veteran's disability rating

    ### Service History Request

    Allows a third-party application to request service history with the authorization
    of a Veteran.

    1. Client Request: GET https://dev-api.va.gov/services/veteran_verification/v0/service_history
       * Provide the Bearer token as a header: `Authorization: Bearer <token>`

    2. Service Response: A JSON API object with the Veteran's complete service history

    ## Reference

    Raw Open API Spec: https://api.va.gov/services/veteran_verification/docs/v0/metadata

  termsOfService: ''
  contact:
    name: VA.gov
servers:
  - url: https://dev-api.va.gov/services/veteran_verification/{version}
    description: VA.gov API development environment
    variables:
      version:
        default: v0
  - url: https://staging-api.va.gov/services/veteran_verification/{version}
    description: VA.gov API staging environment
    variables:
      version:
        default: v0
  - url: https://api.va.gov/services/veteran_verification/{version}
    description: VA.gov API production environment
    variables:
      version:
        default: v0
paths:
  /status: STATUS_DOC_PLACEHOLDER
  /disability_rating: DISABILITY_RATING_DOC_PLACEHOLDER
  /service_history: SERVICE_HISTORY_DOC_PLACEHOLDER
components:
  securitySchemes:
    bearer_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: SCHEMAS_PLACEHOLDER